consul:
  build: .

master:
  build: master/

server:
  build: server/
  links:
    - master

client:
  build: client/
  links:
    - master

haproxy:
  build: haproxy/
  ports:
    - "8080:8080"
    - "8888:8888"
  links:
    - master
