master:
  image: consul:master

server:
  image: consul:server
  links:
    - master

client:
  image: consul:client
  links:
    - master

haproxy:
  image: consul:haproxy
  ports:
    - "8888:8888"
